#!/bin/sh
# xrandr --output HDMI-1-3 --mode 1920x1080 \
#       --rotate right --output DP-1-4 --off \
#       --output HDMI-2 --off
#
# xrandr --output DP-1-4 --mode 1920x1080 --pos 1080x565 \
#       --output HDMI-2 --mode 1920x1080 --right-of DP-1-4


xrandr --output DP-4 --mode 1920x1080 \
      --rotate right --output DP-3 --off \
      --output HDMI-3 --off

xrandr --output DP-3 --mode 1920x1080 --pos 1080x565 \
      --output HDMI-3 --mode 1920x1080 --right-of DP-3

feh --bg-fill /root/images/forest.jpg
#upper screen
#xrandr --output HDMI-1-2 --mode 1920x1080 --pos 1700x-540
