#!/bin/zsh

export DISPLAY=:0
pkillx &
trap "exec pwindow_manager" USR1

(
    trap '' USR1

    #exec X -keeptty :0 vt1 &> /dev/null
    exec X -keeptty :0 vt1 -config /root/xorg.conf

) &
reset

wait
